// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:4000' | (string & {});
};

export type GetPingData = {
    body?: never;
    path?: never;
    query?: {
        name?: string;
    };
    url: '/ping';
};

export type GetPingResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
        hhh2?: string;
        users: Array<{
            id: string;
            name: string;
            email: string;
        }>;
    };
};

export type GetPingResponse = GetPingResponses[keyof GetPingResponses];

export type PostAuthLoginData = {
    body: {
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Default Response
     */
    401: {
        message: string;
    };
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Default Response
     */
    200: {
        user: {
            id: string;
            email: string;
            name: string;
            createdAt: string;
            updatedAt: string;
        };
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];
