// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:4000' | (string & {});
};

export type GetPingData = {
    body?: never;
    path?: never;
    query?: {
        name?: string;
    };
    url: '/ping';
};

export type GetPingResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
        hhh2?: string;
    };
};

export type GetPingResponse = GetPingResponses[keyof GetPingResponses];
