// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:4000' | (string & {});
};

export type GetPingData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Optional name echoed in the pong message
         */
        name?: string;
    };
    url: '/ping';
};

export type GetPingResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
        hhh2?: string;
        users: Array<{
            id: string;
            name: string;
            email: string;
        }>;
    };
};

export type GetPingResponse = GetPingResponses[keyof GetPingResponses];

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Case-insensitive match against name or email
         */
        search?: string;
        /**
         * Only users that have all of these permissions
         */
        permissions?: Array<'write:all' | 'read:all' | 'admin:create:users' | 'admin:read:users' | 'admin:update:users' | 'admin:delete:users' | 'admin:create:roles' | 'admin:read:roles' | 'admin:update:roles' | 'admin:delete:roles' | 'admin:create:permissions' | 'admin:read:permissions' | 'admin:update:permissions' | 'admin:delete:permissions'>;
        /**
         * Include users created on or after this date (UTC)
         */
        createdAtGte?: string;
        /**
         * Include users created on or before this date (UTC)
         */
        createdAtLte?: string;
        /**
         * Sort columns in priority order (id + desc)
         */
        sorting?: Array<{
            id: string;
            desc: boolean;
        }>;
        /**
         * Page size
         */
        limit?: number;
        /**
         * Number of rows to skip
         */
        offset?: number;
    };
    url: '/users';
};

export type GetUsersResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
        result: {
            items: Array<{
                id: string;
                email: string;
                name: string;
                permissions: Array<'write:all' | 'read:all' | 'admin:create:users' | 'admin:read:users' | 'admin:update:users' | 'admin:delete:users' | 'admin:create:roles' | 'admin:read:roles' | 'admin:update:roles' | 'admin:delete:roles' | 'admin:create:permissions' | 'admin:read:permissions' | 'admin:update:permissions' | 'admin:delete:permissions'>;
                createdAt: string;
                updatedAt: string;
            }>;
            total: number;
            limit: number;
            offset: number;
        };
    };
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type PostUsersData = {
    body: {
        /**
         * Display name
         */
        name: string;
        email: string;
        /**
         * Plaintext password (hashed before storage)
         */
        password: string;
        /**
         * Existing role id from GET /roles
         */
        roleId: string;
    };
    path?: never;
    query?: never;
    url: '/users';
};

export type PostUsersErrors = {
    /**
     * Default Response
     */
    400: {
        message: string;
        code: string;
        statusCode: number;
    };
    /**
     * Default Response
     */
    409: {
        message: string;
        code: string;
        statusCode: number;
    };
};

export type PostUsersError = PostUsersErrors[keyof PostUsersErrors];

export type PostUsersResponses = {
    /**
     * Default Response
     */
    201: {
        message: string;
        result: {
            id: string;
            email: string;
            name: string;
            permissions: Array<'write:all' | 'read:all' | 'admin:create:users' | 'admin:read:users' | 'admin:update:users' | 'admin:delete:users' | 'admin:create:roles' | 'admin:read:roles' | 'admin:update:roles' | 'admin:delete:roles' | 'admin:create:permissions' | 'admin:read:permissions' | 'admin:update:permissions' | 'admin:delete:permissions'>;
            createdAt: string;
            updatedAt: string;
        };
    };
};

export type PostUsersResponse = PostUsersResponses[keyof PostUsersResponses];

export type GetSessionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Case-insensitive match against user name or email
         */
        search?: string;
        /**
         * Only sessions belonging to any of these user ids
         */
        userIds?: Array<string>;
        /**
         * Include sessions created on or after this date (UTC)
         */
        createdAtGte?: string;
        /**
         * Include sessions created on or before this date (UTC)
         */
        createdAtLte?: string;
        /**
         * Include sessions expiring on or after this date (UTC)
         */
        expiresAtGte?: string;
        /**
         * Include sessions expiring on or before this date (UTC)
         */
        expiresAtLte?: string;
        /**
         * Sort columns in priority order (id + desc)
         */
        sorting?: Array<{
            id: string;
            desc: boolean;
        }>;
        /**
         * Page size
         */
        limit?: number;
        /**
         * Number of rows to skip
         */
        offset?: number;
    };
    url: '/sessions';
};

export type GetSessionsResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
        result: {
            items: Array<{
                id: string;
                userId: string;
                userEmail: string;
                userName: string;
                expiresAt: string;
                createdAt: string;
                updatedAt: string;
            }>;
            total: number;
            limit: number;
            offset: number;
        };
    };
};

export type GetSessionsResponse = GetSessionsResponses[keyof GetSessionsResponses];

export type GetRolesData = {
    body?: never;
    path?: never;
    query?: {
        search?: string;
        permissions?: Array<'write:all' | 'read:all' | 'admin:create:users' | 'admin:read:users' | 'admin:update:users' | 'admin:delete:users' | 'admin:create:roles' | 'admin:read:roles' | 'admin:update:roles' | 'admin:delete:roles' | 'admin:create:permissions' | 'admin:read:permissions' | 'admin:update:permissions' | 'admin:delete:permissions'>;
        isSystem?: boolean;
        createdAtGte?: string;
        createdAtLte?: string;
        sorting?: Array<{
            id: string;
            desc: boolean;
        }>;
        limit?: number;
        offset?: number;
    };
    url: '/roles';
};

export type GetRolesResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
        result: {
            items: Array<{
                id: string;
                name: string;
                description: string | unknown;
                isSystem: boolean;
                permissions: Array<'write:all' | 'read:all' | 'admin:create:users' | 'admin:read:users' | 'admin:update:users' | 'admin:delete:users' | 'admin:create:roles' | 'admin:read:roles' | 'admin:update:roles' | 'admin:delete:roles' | 'admin:create:permissions' | 'admin:read:permissions' | 'admin:update:permissions' | 'admin:delete:permissions'>;
                createdAt: string;
                updatedAt: string;
            }>;
            total: number;
            limit: number;
            offset: number;
        };
    };
};

export type GetRolesResponse = GetRolesResponses[keyof GetRolesResponses];

export type PostRolesData = {
    body: {
        /**
         * Unique role name (e.g. editor)
         */
        name: string;
        /**
         * Optional human-readable description
         */
        description?: string | unknown;
        /**
         * At least one permission to grant
         */
        permissions: Array<'write:all' | 'read:all' | 'admin:create:users' | 'admin:read:users' | 'admin:update:users' | 'admin:delete:users' | 'admin:create:roles' | 'admin:read:roles' | 'admin:update:roles' | 'admin:delete:roles' | 'admin:create:permissions' | 'admin:read:permissions' | 'admin:update:permissions' | 'admin:delete:permissions'>;
    };
    path?: never;
    query?: never;
    url: '/roles';
};

export type PostRolesErrors = {
    /**
     * Default Response
     */
    409: {
        message: string;
        code: string;
        statusCode: number;
    };
};

export type PostRolesError = PostRolesErrors[keyof PostRolesErrors];

export type PostRolesResponses = {
    /**
     * Default Response
     */
    201: {
        message: string;
        result: {
            id: string;
            name: string;
            description: string | unknown;
            isSystem: boolean;
            permissions: Array<'write:all' | 'read:all' | 'admin:create:users' | 'admin:read:users' | 'admin:update:users' | 'admin:delete:users' | 'admin:create:roles' | 'admin:read:roles' | 'admin:update:roles' | 'admin:delete:roles' | 'admin:create:permissions' | 'admin:read:permissions' | 'admin:update:permissions' | 'admin:delete:permissions'>;
            createdAt: string;
            updatedAt: string;
        };
    };
};

export type PostRolesResponse = PostRolesResponses[keyof PostRolesResponses];

export type PostAuthLoginData = {
    body: {
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Default Response
     */
    401: {
        message: string;
        code: string;
        statusCode: number;
    };
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
        result: {
            id: string;
            email: string;
            name: string;
            createdAt: string;
            updatedAt: string;
        };
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthSignoutData = {
    body: {
        /**
         * Raw session cookie value to revoke
         */
        cookie: string;
    };
    path?: never;
    query?: never;
    url: '/auth/signout';
};

export type PostAuthSignoutResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
        result: unknown;
    };
};

export type PostAuthSignoutResponse = PostAuthSignoutResponses[keyof PostAuthSignoutResponses];

export type PostAuthVerifyData = {
    body: {
        /**
         * Raw session cookie value
         */
        cookie: string;
    };
    path?: never;
    query?: never;
    url: '/auth/verify';
};

export type PostAuthVerifyErrors = {
    /**
     * Default Response
     */
    401: {
        message: string;
        code: string;
        statusCode: number;
    };
};

export type PostAuthVerifyError = PostAuthVerifyErrors[keyof PostAuthVerifyErrors];

export type PostAuthVerifyResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
        result: {
            id: string;
            email: string;
            name: string;
            permissions: Array<'write:all' | 'read:all' | 'admin:create:users' | 'admin:read:users' | 'admin:update:users' | 'admin:delete:users' | 'admin:create:roles' | 'admin:read:roles' | 'admin:update:roles' | 'admin:delete:roles' | 'admin:create:permissions' | 'admin:read:permissions' | 'admin:update:permissions' | 'admin:delete:permissions'>;
        };
    };
};

export type PostAuthVerifyResponse = PostAuthVerifyResponses[keyof PostAuthVerifyResponses];
