services:
  # pgweb:
  #   container_name: plank-pgweb
  #   image: sosedoff/pgweb
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     PGWEB_DATABASE_URL: postgres://plank:plank@postgres.internal:5432/plank?sslmode=disable
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     plank:
  postgres:
    container_name: plank-postgres
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: plank
      POSTGRES_PASSWORD: plank
      POSTGRES_DB: plank
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U plank -d plank"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      plank:
        aliases:
          - postgres.internal

volumes:
  postgres_data:

networks:
  plank:
