// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { deleteUsersById, getPing, getRoles, getSessions, getUsers, type Options, postAuthImpersonate, postAuthLogin, postAuthSignout, postAuthStopImpersonate, postAuthVerify, postRoles, postUsers } from '../sdk.gen';
import type { DeleteUsersByIdData, DeleteUsersByIdError, DeleteUsersByIdResponse, GetPingData, GetPingResponse, GetRolesData, GetRolesResponse, GetSessionsData, GetSessionsResponse, GetUsersData, GetUsersResponse, PostAuthImpersonateData, PostAuthImpersonateError, PostAuthImpersonateResponse, PostAuthLoginData, PostAuthLoginError, PostAuthLoginResponse, PostAuthSignoutData, PostAuthSignoutResponse, PostAuthStopImpersonateData, PostAuthStopImpersonateError, PostAuthStopImpersonateResponse, PostAuthVerifyData, PostAuthVerifyError, PostAuthVerifyResponse, PostRolesData, PostRolesError, PostRolesResponse, PostUsersData, PostUsersError, PostUsersResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getPingQueryKey = (options?: Options<GetPingData>) => createQueryKey('getPing', options);

/**
 * Ping
 *
 * Lightweight health check. Optionally echoes a name and returns a small sample of users to verify DB connectivity.
 */
export const getPingOptions = (options?: Options<GetPingData>) => queryOptions<GetPingResponse, DefaultError, GetPingResponse, ReturnType<typeof getPingQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPing({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPingQueryKey(options)
});

/**
 * Delete user
 *
 * Deletes a user by id. Cascades to sessions, accounts, and role assignments. Returns 400 if you attempt to delete yourself, 404 if the user does not exist.
 */
export const deleteUsersByIdMutation = (options?: Partial<Options<DeleteUsersByIdData>>): UseMutationOptions<DeleteUsersByIdResponse, DeleteUsersByIdError, Options<DeleteUsersByIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteUsersByIdResponse, DeleteUsersByIdError, Options<DeleteUsersByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteUsersById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUsersQueryKey = (options?: Options<GetUsersData>) => createQueryKey('getUsers', options);

/**
 * List users
 *
 * Returns a paginated list of users. Supports search by name/email, permission filters, registration date range, and multi-column sorting.
 */
export const getUsersOptions = (options?: Options<GetUsersData>) => queryOptions<GetUsersResponse, DefaultError, GetUsersResponse, ReturnType<typeof getUsersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUsers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUsersQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getUsersInfiniteQueryKey = (options?: Options<GetUsersData>): QueryKey<Options<GetUsersData>> => createQueryKey('getUsers', options, true);

/**
 * List users
 *
 * Returns a paginated list of users. Supports search by name/email, permission filters, registration date range, and multi-column sorting.
 */
export const getUsersInfiniteOptions = (options?: Options<GetUsersData>) => {
    const opts = infiniteQueryOptions<GetUsersResponse, DefaultError, InfiniteData<GetUsersResponse>, QueryKey<Options<GetUsersData>>, number | Pick<QueryKey<Options<GetUsersData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<GetUsersData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await getUsers({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getUsersInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

/**
 * Create user
 *
 * Creates a user account with the given role and hashed password. Returns 409 if the email is already taken, 400 if the role does not exist.
 */
export const postUsersMutation = (options?: Partial<Options<PostUsersData>>): UseMutationOptions<PostUsersResponse, PostUsersError, Options<PostUsersData>> => {
    const mutationOptions: UseMutationOptions<PostUsersResponse, PostUsersError, Options<PostUsersData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postUsers({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getRolesQueryKey = (options?: Options<GetRolesData>) => createQueryKey('getRoles', options);

/**
 * List roles
 *
 * Paginated, filterable list of roles. Used by the manage-roles table and when assigning a role to a user.
 */
export const getRolesOptions = (options?: Options<GetRolesData>) => queryOptions<GetRolesResponse, DefaultError, GetRolesResponse, ReturnType<typeof getRolesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getRoles({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getRolesQueryKey(options)
});

export const getRolesInfiniteQueryKey = (options?: Options<GetRolesData>): QueryKey<Options<GetRolesData>> => createQueryKey('getRoles', options, true);

/**
 * List roles
 *
 * Paginated, filterable list of roles. Used by the manage-roles table and when assigning a role to a user.
 */
export const getRolesInfiniteOptions = (options?: Options<GetRolesData>) => {
    const opts = infiniteQueryOptions<GetRolesResponse, DefaultError, InfiniteData<GetRolesResponse>, QueryKey<Options<GetRolesData>>, number | Pick<QueryKey<Options<GetRolesData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<GetRolesData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await getRoles({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getRolesInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

/**
 * Create role
 *
 * Creates a custom role with the given name, optional description, and permissions. Returns 409 if the role name is already taken.
 */
export const postRolesMutation = (options?: Partial<Options<PostRolesData>>): UseMutationOptions<PostRolesResponse, PostRolesError, Options<PostRolesData>> => {
    const mutationOptions: UseMutationOptions<PostRolesResponse, PostRolesError, Options<PostRolesData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postRoles({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getSessionsQueryKey = (options?: Options<GetSessionsData>) => createQueryKey('getSessions', options);

/**
 * List sessions
 *
 * Returns a paginated list of auth sessions joined with user identity. Supports search by user name/email, filter by user ids, created/expiry date ranges, and multi-column sorting.
 */
export const getSessionsOptions = (options?: Options<GetSessionsData>) => queryOptions<GetSessionsResponse, DefaultError, GetSessionsResponse, ReturnType<typeof getSessionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSessions({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSessionsQueryKey(options)
});

export const getSessionsInfiniteQueryKey = (options?: Options<GetSessionsData>): QueryKey<Options<GetSessionsData>> => createQueryKey('getSessions', options, true);

/**
 * List sessions
 *
 * Returns a paginated list of auth sessions joined with user identity. Supports search by user name/email, filter by user ids, created/expiry date ranges, and multi-column sorting.
 */
export const getSessionsInfiniteOptions = (options?: Options<GetSessionsData>) => {
    const opts = infiniteQueryOptions<GetSessionsResponse, DefaultError, InfiniteData<GetSessionsResponse>, QueryKey<Options<GetSessionsData>>, number | Pick<QueryKey<Options<GetSessionsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<GetSessionsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await getSessions({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getSessionsInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

/**
 * Start impersonating a user
 *
 * Creates an impersonation session for the given user and sets the httpOnly impersonation cookie. The original session cookie is left unchanged. Requires admin:impersonate or write:all on the real session. Returns 400 if you attempt to impersonate yourself or are already impersonating, 404 if the target user does not exist.
 */
export const postAuthImpersonateMutation = (options?: Partial<Options<PostAuthImpersonateData>>): UseMutationOptions<PostAuthImpersonateResponse, PostAuthImpersonateError, Options<PostAuthImpersonateData>> => {
    const mutationOptions: UseMutationOptions<PostAuthImpersonateResponse, PostAuthImpersonateError, Options<PostAuthImpersonateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthImpersonate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Log in
 *
 * Authenticates with email and password, creates a session, and sets the httpOnly session cookie. Returns 401 when credentials are invalid.
 */
export const postAuthLoginMutation = (options?: Partial<Options<PostAuthLoginData>>): UseMutationOptions<PostAuthLoginResponse, PostAuthLoginError, Options<PostAuthLoginData>> => {
    const mutationOptions: UseMutationOptions<PostAuthLoginResponse, PostAuthLoginError, Options<PostAuthLoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthLogin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Sign out
 *
 * Revokes the given session and optional impersonation session (if still valid) and clears both cookies. Always succeeds so the client can clear local auth state.
 */
export const postAuthSignoutMutation = (options?: Partial<Options<PostAuthSignoutData>>): UseMutationOptions<PostAuthSignoutResponse, DefaultError, Options<PostAuthSignoutData>> => {
    const mutationOptions: UseMutationOptions<PostAuthSignoutResponse, DefaultError, Options<PostAuthSignoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthSignout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Stop impersonating
 *
 * Revokes the impersonation session and clears the impersonation cookie. The original session cookie is left intact so the admin is restored. Returns 400 when not currently impersonating.
 */
export const postAuthStopImpersonateMutation = (options?: Partial<Options<PostAuthStopImpersonateData>>): UseMutationOptions<PostAuthStopImpersonateResponse, PostAuthStopImpersonateError, Options<PostAuthStopImpersonateData>> => {
    const mutationOptions: UseMutationOptions<PostAuthStopImpersonateResponse, PostAuthStopImpersonateError, Options<PostAuthStopImpersonateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthStopImpersonate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Verify session
 *
 * Validates session cookies and returns the effective authenticated user with permissions. When an impersonation cookie is present and valid, returns the impersonated user and the impersonator. Otherwise validates the session cookie. Returns 401 when no valid session exists.
 */
export const postAuthVerifyMutation = (options?: Partial<Options<PostAuthVerifyData>>): UseMutationOptions<PostAuthVerifyResponse, PostAuthVerifyError, Options<PostAuthVerifyData>> => {
    const mutationOptions: UseMutationOptions<PostAuthVerifyResponse, PostAuthVerifyError, Options<PostAuthVerifyData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthVerify({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
